{
 "title": "Red Hat JBoss EAP XP 3.0 Cloud Ready",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Application GetList method execution time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "application_checksTimer_seconds"
    }
   ]
  },
  {
   "title": "JVM Memory heap",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "base_memory_usedHeap_bytes" }
   ]
  },
  {
   "title": "JBoss Cloud Ready total request",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "application_com_redhat_example_weather_WeatherService_requestCount_total"
    }
   ]
  },
  {
   "title": "Active DataSource connection",
   "type": "stat",
   "description": "The number of active connections. Each of the connections is either in use by an application or available in the pool. ",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "jboss_datasources_pool_active_count"
    }
   ]
  }
 ]
}