kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: health
  namespace: redhat-jboss-eap-cloud-ready-demo
  labels:
    app: weather-app-eap-cloud-ready
spec:
  path: /health
  to:
    kind: Service
    name: weather-app-eap-cloud-ready
  port:
    targetPort: 9990
  wildcardPolicy: None